targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/features/**/models/*.dart
          - lib/features/**/entities/*.dart
      json_serializable:
        generate_for:
          - lib/features/**/models/*.dart
          - lib/features/**/entities/*.dart
      injectable_generator|injectable_builder:
        generate_for:
          - lib/**.dart
