// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJA8L_Pe3EKwuRIqH2ZXFso2mSvRkY4XU',
    appId: '1:1063937262701:web:d875fe7489e12cba37ab64',
    messagingSenderId: '1063937262701',
    projectId: 'finos-158cf',
    authDomain: 'finos-158cf.firebaseapp.com',
    storageBucket: 'finos-158cf.firebasestorage.app',
    measurementId: 'G-51GGKBGWEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdnmu6wEJkKcqhss6pWQAuUEIkIHh7PUI',
    appId: '1:1063937262701:android:ce089a5962af122437ab64',
    messagingSenderId: '1063937262701',
    projectId: 'finos-158cf',
    storageBucket: 'finos-158cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bKR2H0wT-EUy4MYPQEVe7xi7K4zaFX8',
    appId: '1:1063937262701:ios:7add556f03c7da7a37ab64',
    messagingSenderId: '1063937262701',
    projectId: 'finos-158cf',
    storageBucket: 'finos-158cf.firebasestorage.app',
    iosBundleId: 'com.example.finos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bKR2H0wT-EUy4MYPQEVe7xi7K4zaFX8',
    appId: '1:1063937262701:ios:7add556f03c7da7a37ab64',
    messagingSenderId: '1063937262701',
    projectId: 'finos-158cf',
    storageBucket: 'finos-158cf.firebasestorage.app',
    iosBundleId: 'com.example.finos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJA8L_Pe3EKwuRIqH2ZXFso2mSvRkY4XU',
    appId: '1:1063937262701:web:9ca4a1fb1be0202637ab64',
    messagingSenderId: '1063937262701',
    projectId: 'finos-158cf',
    authDomain: 'finos-158cf.firebaseapp.com',
    storageBucket: 'finos-158cf.firebasestorage.app',
    measurementId: 'G-0FWZV8W514',
  );
}
